---
abstract: 'TT Filter Plugin for Lingua::JA::Regular::Unicode.'
author:
  - 'YAMAMOTO Ryuzo (dragon3) <ryuzo.yamamoto@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-Lingua-JA-Regular-Unicode
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  Lingua::JA::Regular::Unicode: 0
  Template: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
